web:
    image: oneklc/wp-grinone-com
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
    ports:
     - "127.0.0.3:8080:80"
    working_dir: /var/www/html
    volumes:
     - wordpress/wp-content/:/var/www/html/wp-content

mysql:
    image: oneklc/wp-grinone-com-mysql
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
